<a href="https://colab.research.google.com/github/jagannadha29/DAE-in-google-colab/blob/main/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
# PROGRAM A - BASIC ndarray
# Example A1 - Comparison of Monthly Electricity Bills
import numpy as np
print("="*70)
print("EXAMPLE A1 : MONTHLY ELECTRICITY BILL COMPARISON")
print("="*70)

electricity_bill_2025 = np.array([1620, 1715, 1680, 1825, 1900, 1845, 1780, 1860])

electricity_bill_2026 = np.array([1695, 1760, 1735, 1880, 1945, 1910, 1835, 1925])

print("\nElectricity Bills - 2025")
print(electricity_bill_2025)

print("\nElectricity Bills - 2026")
print(electricity_bill_2026)

average_2025 = np.mean(electricity_bill_2025)
average_2026 = np.mean(electricity_bill_2026)

print("\n1. Average Comparison")
print(f"Average Bill (2025): ₹{average_2025:.2f}")
print(f"Average Bill (2026): ₹{average_2026:.2f}")
print(f"Higher Average Difference: ₹{abs(average_2026-average_2025):.2f}")

comparison_result = electricity_bill_2025 > electricity_bill_2026

print("\n2. Number of months where 2025 bill exceeded 2026 bill")
print(np.sum(comparison_result))

maximum_gap = np.max(electricity_bill_2026) - np.max(electricity_bill_2025)

print("\n3. Gap Between Maximum Bills")
print(f"Maximum Bill Difference = ₹{maximum_gap}")

EXAMPLE A1 : MONTHLY ELECTRICITY BILL COMPARISON

Electricity Bills - 2025
[1620 1715 1680 1825 1900 1845 1780 1860]

Electricity Bills - 2026
[1695 1760 1735 1880 1945 1910 1835 1925]

1. Average Comparison
Average Bill (2025): ₹1778.12
Average Bill (2026): ₹1835.62
Higher Average Difference: ₹57.50

2. Number of months where 2025 bill exceeded 2026 bill
0

3. Gap Between Maximum Bills
Maximum Bill Difference = ₹45


In [25]:
# Example A2 - Weekly Grocery Expense Trend
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE A2 : WEEKLY GROCERY EXPENSE TREND")
print("="*70)

weekly_grocery_expense = np.array([2350, 2420, 2480, 2550, 2610,
                                   2680, 2745, 2815, 2890, 2960])

print("\nWeekly Grocery Expenses")
print(weekly_grocery_expense)

overall_change = weekly_grocery_expense[-1] - weekly_grocery_expense[0]

print("\n1. Overall Trend")
print(f"Overall Change = ₹{overall_change}")

print("Trend : Increasing")

expense_range = np.max(weekly_grocery_expense) - np.min(weekly_grocery_expense)

print("\n2. Expense Range")
print(f"Range = ₹{expense_range}")

average_expense = np.mean(weekly_grocery_expense)

above_average = weekly_grocery_expense > average_expense

print("\n3. Weeks Above Average Expense")
print(np.sum(above_average))



EXAMPLE A2 : WEEKLY GROCERY EXPENSE TREND

Weekly Grocery Expenses
[2350 2420 2480 2550 2610 2680 2745 2815 2890 2960]

1. Overall Trend
Overall Change = ₹610
Trend : Increasing

2. Expense Range
Range = ₹610

3. Weeks Above Average Expense
5


In [26]:
# Example A3 - Laptop Prices Filter
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE A3 : LAPTOP PRICE FILTER")
print("="*70)

laptop_prices = np.array([48990, 52990, 57500, 61250, 64800,
                          68990, 72499, 78990, 84500, 91990])

print("\nLaptop Prices")
print(laptop_prices)

average_price = np.mean(laptop_prices)

print("\nAverage Laptop Price")
print(f"₹{average_price:.2f}")

expensive_laptops = laptop_prices[laptop_prices > average_price]

print("\n1. Number of Laptop Prices Above Average")
print(expensive_laptops.size)

print("\n2. Laptop Prices Above Average")
print(expensive_laptops)

percentage = (expensive_laptops.size / laptop_prices.size) * 100

print("\n3. Percentage of Laptops Above Average")
print(f"{percentage:.2f}%")



EXAMPLE A3 : LAPTOP PRICE FILTER

Laptop Prices
[48990 52990 57500 61250 64800 68990 72499 78990 84500 91990]

Average Laptop Price
₹68249.90

1. Number of Laptop Prices Above Average
5

2. Laptop Prices Above Average
[68990 72499 78990 84500 91990]

3. Percentage of Laptops Above Average
50.00%


In [27]:
# PROGRAM B - ARRAY OF ZEROS
# Example B1 - College Library Book Reservation System
import numpy as np
print("="*70)
print("EXAMPLE B1 : COLLEGE LIBRARY BOOK RESERVATION SYSTEM")
print("="*70)

book_slots = np.zeros(20, dtype=int)

# Updating reserved book slots
book_slots[[0,2,3,5,6,8,9,11,12,15,17,18]] = 1

print("\nReservation Status")
print(book_slots)

available_slots = np.sum(book_slots == 0)
utilization = (np.sum(book_slots) / book_slots.size) * 100

print("\n1. Available Book Slots")
print(available_slots)

print("\n2. Capacity Utilized")
print(f"{utilization:.2f}%")

print("\n3. More than 60% of slots are occupied:")
print(utilization > 60)

EXAMPLE B1 : COLLEGE LIBRARY BOOK RESERVATION SYSTEM

Reservation Status
[1 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 1 0]

1. Available Book Slots
8

2. Capacity Utilized
60.00%

3. More than 60% of slots are occupied:
False


In [28]:
# Example B2 - Monthly Savings Tracker
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE B2 : MONTHLY SAVINGS TRACKER")
print("="*70)

monthly_savings = np.zeros(12, dtype=int)

monthly_savings[[0,1,2,4,5,7,9]] = [2500,3200,2800,3500,4100,3900,4500]

print("\nMonthly Savings")
print(monthly_savings)

total_savings = np.sum(monthly_savings)

remaining_months = np.sum(monthly_savings == 0)

target_savings = 50000
remaining_amount = target_savings - total_savings

print("\n1. Total Savings")
print(f"₹{total_savings}")

print("\n2. Months Still Not Recorded")
print(remaining_months)

print("\n3. Amount Remaining to Reach Target")
print(f"₹{remaining_amount}")



EXAMPLE B2 : MONTHLY SAVINGS TRACKER

Monthly Savings
[2500 3200 2800    0 3500 4100    0 3900    0 4500    0    0]

1. Total Savings
₹24500

2. Months Still Not Recorded
5

3. Amount Remaining to Reach Target
₹25500


In [29]:
# Example B3 - Quiz Scoreboard
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE B3 : QUIZ SCOREBOARD")
print("="*70)

quiz_scores = np.zeros(8, dtype=int)

quiz_scores[:] = [18,15,20,12,17,0,19,14]

student_names = np.array([
    "Anil",
    "Bhavya",
    "Charan",
    "Divya",
    "Esha",
    "Farhan",
    "Gowtham",
    "Harsha"
])

print("\nStudent Names")
print(student_names)

print("\nQuiz Scores")
print(quiz_scores)

highest_score = np.max(quiz_scores)
lowest_score = np.min(quiz_scores)
margin = highest_score - lowest_score

leader = student_names[np.argmax(quiz_scores)]
last_place = student_names[np.argmin(quiz_scores)]

print("\n1. Leader and Margin")
print("Leader :", leader)
print("Last Place :", last_place)
print("Margin :", margin)

print("\n2. Students Still at Zero Score")
print(student_names[quiz_scores == 0])

print("Meaning: These students have not scored any marks yet.")

average_score = np.mean(quiz_scores)

print("\n3. Average Score")
print(f"{average_score:.2f}")



EXAMPLE B3 : QUIZ SCOREBOARD

Student Names
['Anil' 'Bhavya' 'Charan' 'Divya' 'Esha' 'Farhan' 'Gowtham' 'Harsha']

Quiz Scores
[18 15 20 12 17  0 19 14]

1. Leader and Margin
Leader : Charan
Last Place : Farhan
Margin : 20

2. Students Still at Zero Score
['Farhan']
Meaning: These students have not scored any marks yet.

3. Average Score
14.38


In [30]:
# PROGRAM C - ARRAY OF ONES
# Example C1 - Festival Discount System
import numpy as np
print("="*70)
print("EXAMPLE C1 : FESTIVAL DISCOUNT SYSTEM")
print("="*70)

product_names = np.array([
    "Laptop","Smartphone","Headphones","Backpack",
    "Shoes","Watch","Speaker","Keyboard"
])

original_prices = np.array([65000,32000,4500,2500,3200,6000,7500,2800])

price_multipliers = np.ones(8)

price_multipliers[[0,1]] = 0.90      # 10% discount
price_multipliers[[2,3]] = 0.85      # 15% discount
price_multipliers[[4,5]] = 0.80      # 20% discount
price_multipliers[[6,7]] = 0.95      # 5% discount

discounted_prices = original_prices * price_multipliers

full_revenue = np.sum(original_prices)
discounted_revenue = np.sum(discounted_prices)

discount_amount = original_prices - discounted_prices

print("\nProducts")
print(product_names)

print("\nOriginal Prices")
print(original_prices)

print("\nDiscounted Prices")
print(discounted_prices)

print("\n1. Revenue Comparison")
print("Revenue at Full Price : ₹", full_revenue)
print("Revenue After Discount : ₹", discounted_revenue)

print("\n2. Best Deal")
print(product_names[np.argmax(discount_amount)])
print("Discount : ₹", np.max(discount_amount))

revenue_loss = ((full_revenue - discounted_revenue)/full_revenue)*100

print("\n3. Percentage Revenue Lost")
print(f"{revenue_loss:.2f}%")

EXAMPLE C1 : FESTIVAL DISCOUNT SYSTEM

Products
['Laptop' 'Smartphone' 'Headphones' 'Backpack' 'Shoes' 'Watch' 'Speaker'
 'Keyboard']

Original Prices
[65000 32000  4500  2500  3200  6000  7500  2800]

Discounted Prices
[58500. 28800.  3825.  2125.  2560.  4800.  7125.  2660.]

1. Revenue Comparison
Revenue at Full Price : ₹ 123500
Revenue After Discount : ₹ 110395.0

2. Best Deal
Laptop
Discount : ₹ 6500.0

3. Percentage Revenue Lost
10.61%


In [31]:
# Example C2 - Semester Subject Weight System
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE C2 : SEMESTER SUBJECT WEIGHT SYSTEM")
print("="*70)

student_names = np.array(["Akhil","Bhanu","Charan","Deepa"])

student_marks = np.array([
    [82,76,88,91,84],
    [74,81,79,85,80],
    [90,89,92,94,91],
    [78,84,83,80,86]
])

subject_weights = np.ones(5)

subject_weights[[0,1]] = 1.5      # Core subjects
subject_weights[[2]] = 2.0        # Lab
subject_weights[[3]] = 1.0
subject_weights[[4]] = 1.2

simple_average = np.mean(student_marks, axis=1)

weighted_average = np.average(student_marks,
                              axis=1,
                              weights=subject_weights)

difference = weighted_average - simple_average

print("\nSimple Average")
print(simple_average)

print("\nWeighted Average")
print(weighted_average)

print("\n1. Difference Between Weighted and Simple Average")
print(difference)

print("\n2. Student Benefited Most")
print(student_names[np.argmax(difference)])

print("\nStudent Disadvantaged Most")
print(student_names[np.argmin(difference)])

print("\n3. Difference for Each Student")
print(difference)




EXAMPLE C2 : SEMESTER SUBJECT WEIGHT SYSTEM

Simple Average
[84.2 79.8 91.2 82.2]

Weighted Average
[84.         79.375      91.06944444 82.25      ]

1. Difference Between Weighted and Simple Average
[-0.2        -0.425      -0.13055556  0.05      ]

2. Student Benefited Most
Deepa

Student Disadvantaged Most
Bhanu

3. Difference for Each Student
[-0.2        -0.425      -0.13055556  0.05      ]


In [32]:
# Example C3 - Employee Performance Multiplier
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE C3 : EMPLOYEE PERFORMANCE MULTIPLIER")
print("="*70)

employee_names = np.array([
    "Ajay","Bharath","Chandu","Dinesh",
    "Eswar","Farooq","Ganesh","Harish"
])

base_salary = 30000

performance_multiplier = np.ones(8)

performance_multiplier[:] = [1.20,1.10,0.95,1.35,
                             1.05,1.25,0.90,1.15]

final_salary = base_salary * performance_multiplier

salary_range = np.max(final_salary) - np.min(final_salary)

average_multiplier = np.mean(performance_multiplier)

above_average = np.sum(final_salary > np.mean(final_salary))

print("\nEmployee Names")
print(employee_names)

print("\nPerformance Multipliers")
print(performance_multiplier)

print("\nFinal Salaries")
print(final_salary)

print("\n1. Range Between Highest and Lowest Salary")
print(f"₹{salary_range:.2f}")

print("\n2. Average Multiplier")
print(f"{average_multiplier:.2f}")

print("\n3. Employees Above Group Average")
print(above_average)



EXAMPLE C3 : EMPLOYEE PERFORMANCE MULTIPLIER

Employee Names
['Ajay' 'Bharath' 'Chandu' 'Dinesh' 'Eswar' 'Farooq' 'Ganesh' 'Harish']

Performance Multipliers
[1.2  1.1  0.95 1.35 1.05 1.25 0.9  1.15]

Final Salaries
[36000. 33000. 28500. 40500. 31500. 37500. 27000. 34500.]

1. Range Between Highest and Lowest Salary
₹13500.00

2. Average Multiplier
1.12

3. Employees Above Group Average
4


In [33]:
# PROGRAM D - RANDOM NUMBERS IN ndarray
# Example D1 - Student Sleep Hours Survey Simulator
import numpy as np
np.random.seed(123456)
print("="*70)
print("EXAMPLE D1 : STUDENT SLEEP HOURS SURVEY")
print("="*70)

sleep_hours = np.random.uniform(4, 10, 40)

print("\nSimulated Sleep Hours")
print(np.round(sleep_hours, 2))

average_sleep = np.mean(sleep_hours)

healthy_students = sleep_hours[
    (sleep_hours >= 7) &
    (sleep_hours <= 9)
]

healthy_percentage = (healthy_students.size / sleep_hours.size) * 100

top_10_percent = sleep_hours[
    sleep_hours >= np.percentile(sleep_hours, 90)
]

print("\n1. Average Sleep Hours")
print(f"{average_sleep:.2f} hours")

print("\n2. Students within Healthy Range (7-9 hours)")
print(f"{healthy_percentage:.2f}%")

print("\n3. Top 10% (Above 90th Percentile)")
print(np.round(top_10_percent,2))

EXAMPLE D1 : STUDENT SLEEP HOURS SURVEY

Simulated Sleep Hours
[4.76 9.8  5.56 9.38 6.26 6.02 6.71 9.04 4.74 7.26 6.24 6.69 4.78 9.16
 8.92 6.11 5.37 8.66 7.57 4.83 9.12 5.41 4.88 7.54 7.44 4.37 7.54 5.47
 6.04 9.91 9.52 4.23 9.17 8.52 6.43 6.06 5.03 6.37 7.85 5.65]

1. Average Sleep Hours
6.86 hours

2. Students within Healthy Range (7-9 hours)
22.50%

3. Top 10% (Above 90th Percentile)
[9.8  9.38 9.91 9.52]


In [34]:
# Example D2 - Tea Stall Daily Customer Simulator
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE D2 : TEA STALL CUSTOMER SIMULATION")
print("="*70)

daily_customers = np.random.randint(20,81,30)

print("\nDaily Customers")
print(daily_customers)

peak_day = np.argmax(daily_customers) + 1
off_peak_day = np.argmin(daily_customers) + 1

monthly_total = np.sum(daily_customers)

target = 55

above_target_percentage = (
    np.sum(daily_customers > target)
    / daily_customers.size
) * 100

print("\n1. Peak Day")
print("Day", peak_day, "-", np.max(daily_customers), "customers")

print("\nOff Peak Day")
print("Day", off_peak_day, "-", np.min(daily_customers), "customers")

print("\n2. Projected Monthly Total")
print(monthly_total)

print("\n3. Percentage of Days Above Target")
print(f"{above_target_percentage:.2f}%")



EXAMPLE D2 : TEA STALL CUSTOMER SIMULATION

Daily Customers
[38 80 57 70 73 76 39 32 50 48 62 45 71 22 55 29 48 68 23 52 57 69 24 48
 38 62 27 65 49 37]

1. Peak Day
Day 2 - 80 customers

Off Peak Day
Day 14 - 22 customers

2. Projected Monthly Total
1514

3. Percentage of Days Above Target
40.00%


In [35]:
# Example D3 - Monte Carlo Simulation
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE D3 : MONTE CARLO MARKS SIMULATION")
print("="*70)

np.random.seed(123456)

marks_run1 = np.random.randint(35,101,1000)

fraction_above_75_run1 = (
    np.sum(marks_run1 > 75)
    / marks_run1.size
)

print("\nRun 1")
print("Fraction Above 75 =", fraction_above_75_run1)

np.random.seed(654321)

marks_run2 = np.random.randint(35,101,1000)

fraction_above_75_run2 = (
    np.sum(marks_run2 > 75)
    / marks_run2.size
)

difference = abs(
    fraction_above_75_run1 -
    fraction_above_75_run2
)

print("\nRun 2")
print("Fraction Above 75 =", fraction_above_75_run2)

print("\nDifference Between Runs")
print(difference)



EXAMPLE D3 : MONTE CARLO MARKS SIMULATION

Run 1
Fraction Above 75 = 0.384

Run 2
Fraction Above 75 = 0.345

Difference Between Runs
0.039000000000000035


In [36]:
# PROGRAM E - AN ARRAY OF YOUR CHOICE
# Example E1 - Daily Water Consumption
import numpy as np
print("="*70)
print("EXAMPLE E1 : DAILY WATER CONSUMPTION")
print("="*70)

daily_water_intake = np.array([2.8, 3.1, 2.9, 3.4, 3.0, 2.7, 3.3])

print("\nDaily Water Intake (Litres)")
print(daily_water_intake)

average_water = np.mean(daily_water_intake)

print("\nAverage Daily Water Intake")
print(f"{average_water:.2f} Litres")

print("\nHighest Water Intake")
print(f"{np.max(daily_water_intake):.2f} Litres")

print("\nLowest Water Intake")
print(f"{np.min(daily_water_intake):.2f} Litres")

print("\nDifference from 3-Litre Target")
print(f"{average_water-3:.2f} Litres")


EXAMPLE E1 : DAILY WATER CONSUMPTION

Daily Water Intake (Litres)
[2.8 3.1 2.9 3.4 3.  2.7 3.3]

Average Daily Water Intake
3.03 Litres

Highest Water Intake
3.40 Litres

Lowest Water Intake
2.70 Litres

Difference from 3-Litre Target
0.03 Litres


In [37]:
# Example E2 - Runs of Virat Kohli in Recent Innings
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE E2 : VIRAT KOHLI RECENT RUNS")
print("="*70)

virat_runs = np.array([42, 78, 56, 91, 63, 38, 84, 72])

print("\nRuns")
print(virat_runs)

average_runs = np.mean(virat_runs)

highest_score = np.max(virat_runs)

lowest_score = np.min(virat_runs)

scores_above_average = virat_runs[virat_runs > average_runs]

print("\nAverage Runs")
print(f"{average_runs:.2f}")

print("\nHighest Score")
print(highest_score)

print("\nLowest Score")
print(lowest_score)

print("\nScores Above Average")
print(scores_above_average)



EXAMPLE E2 : VIRAT KOHLI RECENT RUNS

Runs
[42 78 56 91 63 38 84 72]

Average Runs
65.50

Highest Score
91

Lowest Score
38

Scores Above Average
[78 91 84 72]


In [38]:
# Example E3 - Daily Mobile Usage
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE E3 : DAILY MOBILE USAGE ANALYSIS")
print("="*70)

mobile_usage = np.array([3.8, 5.6, 4.7, 6.2, 4.1, 5.9, 4.8, 5.1])

print("\nDaily Mobile Usage (Hours)")
print(mobile_usage)

average_usage = np.mean(mobile_usage)

maximum_usage = np.max(mobile_usage)

minimum_usage = np.min(mobile_usage)

usage_range = maximum_usage - minimum_usage

above_average_usage = mobile_usage[mobile_usage > average_usage]

percentage_above_average = (above_average_usage.size / mobile_usage.size) * 100

print("\nAverage Usage")
print(f"{average_usage:.2f} Hours")

print("\nMaximum Usage")
print(f"{maximum_usage:.2f} Hours")

print("\nMinimum Usage")
print(f"{minimum_usage:.2f} Hours")

print("\nUsage Range")
print(f"{usage_range:.2f} Hours")

print("\nDays Above Average Usage")
print(above_average_usage)

print("\nPercentage of Days Above Average")
print(f"{percentage_above_average:.2f}%")



EXAMPLE E3 : DAILY MOBILE USAGE ANALYSIS

Daily Mobile Usage (Hours)
[3.8 5.6 4.7 6.2 4.1 5.9 4.8 5.1]

Average Usage
5.02 Hours

Maximum Usage
6.20 Hours

Minimum Usage
3.80 Hours

Usage Range
2.40 Hours

Days Above Average Usage
[5.6 6.2 5.9 5.1]

Percentage of Days Above Average
50.00%


In [39]:
# PROGRAM F - IDENTITY MATRIX IN NUMPY
# Example F1 - The No-Change Proof
import numpy as np
print("="*70)
print("EXAMPLE F1 : THE NO-CHANGE PROOF")
print("="*70)

student_marks = np.array([
    [85, 78, 92],
    [76, 88, 81],
    [91, 84, 89]
])

identity_matrix = np.eye(3)

print("\nOriginal Matrix")
print(student_marks)

result_right = np.dot(student_marks, identity_matrix)
result_left = np.dot(identity_matrix, student_marks)

print("\nA × I")
print(result_right)

print("\nI × A")
print(result_left)

print("\n1. Does A × I = A ?")
print(np.array_equal(student_marks, result_right))

print("\n2. Does I × A = A ?")
print(np.array_equal(student_marks, result_left))

EXAMPLE F1 : THE NO-CHANGE PROOF

Original Matrix
[[85 78 92]
 [76 88 81]
 [91 84 89]]

A × I
[[85. 78. 92.]
 [76. 88. 81.]
 [91. 84. 89.]]

I × A
[[85. 78. 92.]
 [76. 88. 81.]
 [91. 84. 89.]]

1. Does A × I = A ?
True

2. Does I × A = A ?
True


In [40]:
# Example F2 - Salary Increment Matrix
import numpy as np
print("\n\n" + "="*70)
print("EXAMPLE F2 : SALARY INCREMENT MATRIX")
print("="*70)

salary_identity = np.eye(4)

increment_matrix = salary_identity.copy()

increment_matrix[0,0] = 1.10
increment_matrix[1,1] = 1.15
increment_matrix[2,2] = 1.08
increment_matrix[3,3] = 1.12

print("\nBefore Increment")
print(salary_identity)

print("\nAfter Increment")
print(increment_matrix)

print("\n1. Baseline Matrix")
print(salary_identity)

print("\n2. Updated Matrix")
print(increment_matrix)




EXAMPLE F2 : SALARY INCREMENT MATRIX

Before Increment
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

After Increment
[[1.1  0.   0.   0.  ]
 [0.   1.15 0.   0.  ]
 [0.   0.   1.08 0.  ]
 [0.   0.   0.   1.12]]

1. Baseline Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

2. Updated Matrix
[[1.1  0.   0.   0.  ]
 [0.   1.15 0.   0.  ]
 [0.   0.   1.08 0.  ]
 [0.   0.   0.   1.12]]


In [41]:
# Example F3 - Pattern Discovery
import numpy as np
print("\n\n" + "="*70)
print("EXAMPLE F3 : PATTERN DISCOVERY")
print("="*70)

identity2 = np.eye(2)
identity3 = np.eye(3)
identity4 = np.eye(4)
identity5 = np.eye(5)

trace_values = np.array([
    np.trace(identity2),
    np.trace(identity3),
    np.trace(identity4),
    np.trace(identity5)
])

determinant_values = np.array([
    np.linalg.det(identity2),
    np.linalg.det(identity3),
    np.linalg.det(identity4),
    np.linalg.det(identity5)
])

print("\nTrace Values")
print(trace_values)

print("\nDeterminant Values")
print(determinant_values)

print("\nMatrix Sizes")
print(np.array([2,3,4,5]))



EXAMPLE F3 : PATTERN DISCOVERY

Trace Values
[2. 3. 4. 5.]

Determinant Values
[1. 1. 1. 1.]

Matrix Sizes
[2 3 4 5]


In [42]:
# PROGRAM G - EVENLY SPACED ndarray
# Example G1 - Customer Satisfaction Rating Scale
import numpy as np
print("="*70)
print("EXAMPLE G1 : CUSTOMER SATISFACTION SCALE")
print("="*70)

rating_scale = np.linspace(0, 10, 11)

customer_ratings = np.array([2, 5, 6, 7, 9])

print("\nRating Scale")
print(rating_scale)

print("\nCustomer Ratings")
print(customer_ratings)

low_zone = customer_ratings[customer_ratings <= 3]
medium_zone = customer_ratings[(customer_ratings > 3) & (customer_ratings <= 7)]
high_zone = customer_ratings[customer_ratings > 7]

print("\nLow Zone")
print(low_zone)

print("\nMedium Zone")
print(medium_zone)

print("\nHigh Zone")
print(high_zone)

print("\nPercentage in Low Zone")
print(f"{(low_zone.size/customer_ratings.size)*100:.2f}%")

print("\nPercentage in Medium Zone")
print(f"{(medium_zone.size/customer_ratings.size)*100:.2f}%")

print("\nPercentage in High Zone")
print(f"{(high_zone.size/customer_ratings.size)*100:.2f}%")

EXAMPLE G1 : CUSTOMER SATISFACTION SCALE

Rating Scale
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Customer Ratings
[2 5 6 7 9]

Low Zone
[2]

Medium Zone
[5 6 7]

High Zone
[9]

Percentage in Low Zone
20.00%

Percentage in Medium Zone
60.00%

Percentage in High Zone
20.00%


In [43]:
# Example G2 - College Bus Schedule
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE G2 : COLLEGE BUS SCHEDULE")
print("="*70)

bus_schedule = np.arange(6, 22.5, 0.5)

print("\nBus Timings (Hours)")
print(bus_schedule)

print("\n1. Total Slots")
print(bus_schedule.size)

mid_slot = (bus_schedule.size // 2) + 1

print("\n2. Slot Closest to Midpoint")
print(mid_slot)

remaining_slots = bus_schedule.size - 3

utilization = (remaining_slots / bus_schedule.size) * 100

print("\n3. Remaining Slots After Cancelling 3")
print(remaining_slots)

print("Utilization Rate")
print(f"{utilization:.2f}%")



EXAMPLE G2 : COLLEGE BUS SCHEDULE

Bus Timings (Hours)
[ 6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5
 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5
 20.  20.5 21.  21.5 22. ]

1. Total Slots
33

2. Slot Closest to Midpoint
17

3. Remaining Slots After Cancelling 3
30
Utilization Rate
90.91%


In [44]:
# Example G3 - Discount Threshold Discovery
import numpy as np
print("\n\n"+"="*70)
print("EXAMPLE G3 : DISCOUNT THRESHOLD DISCOVERY")
print("="*70)

discount_percentages = np.arange(5, 51, 1)

discounted_prices = 999 * (1 - discount_percentages / 100)

threshold_discount = discount_percentages[discounted_prices < 699][0]

threshold_price = discounted_prices[discounted_prices < 699][0]

print("\nDiscount Percentages")
print(discount_percentages)

print("\nDiscounted Prices")
print(np.round(discounted_prices,2))

print("\n1. Threshold Discount")
print(f"{threshold_discount}%")

print("Price at Threshold")
print(f"₹{threshold_price:.2f}")



EXAMPLE G3 : DISCOUNT THRESHOLD DISCOVERY

Discount Percentages
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Discounted Prices
[949.05 939.06 929.07 919.08 909.09 899.1  889.11 879.12 869.13 859.14
 849.15 839.16 829.17 819.18 809.19 799.2  789.21 779.22 769.23 759.24
 749.25 739.26 729.27 719.28 709.29 699.3  689.31 679.32 669.33 659.34
 649.35 639.36 629.37 619.38 609.39 599.4  589.41 579.42 569.43 559.44
 549.45 539.46 529.47 519.48 509.49 499.5 ]

1. Threshold Discount
31%
Price at Threshold
₹689.31
